# Generated by Django 5.0.4 on 2024-04-05 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EarlyDiagnosisPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('id_number', models.CharField(max_length=19)),
                ('address', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=20)),
                ('age', models.IntegerField(max_length=4)),
                ('gender', models.CharField(max_length=7)),
                ('polyuria', models.CharField(max_length=5)),
                ('polydipsia', models.CharField(max_length=5)),
                ('sudden_weight_loss', models.CharField(max_length=5)),
                ('weakness', models.CharField(max_length=5)),
                ('polyphagia', models.CharField(max_length=5)),
                ('genital_thrush', models.CharField(max_length=5)),
                ('visual_blurring', models.CharField(max_length=5)),
                ('itching', models.CharField(max_length=5)),
                ('irritability', models.CharField(max_length=5)),
                ('delayed_healing', models.CharField(max_length=5)),
                ('partial_paresis', models.CharField(max_length=5)),
                ('muscle_stiffness', models.CharField(max_length=5)),
                ('alopecia', models.CharField(max_length=5)),
                ('obesity', models.CharField(max_length=5)),
                ('height', models.CharField(max_length=7)),
                ('mass', models.CharField(max_length=7)),
                ('status', models.CharField(default=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('id_number', models.CharField(max_length=17)),
                ('sex', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=20)),
                ('pregnancies', models.IntegerField(max_length=2)),
                ('glucose_level', models.FloatField()),
                ('blood_pressure', models.FloatField()),
                ('skin_thickness', models.FloatField()),
                ('insulin', models.FloatField()),
                ('BMI', models.FloatField()),
                ('Diabetes_Pedigree_Function', models.FloatField()),
                ('age', models.IntegerField(max_length=3)),
                ('height', models.FloatField()),
                ('mass', models.FloatField()),
                ('status', models.CharField(default=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(null=True)),
                ('pdf', models.FileField(blank=True, upload_to='media')),
                ('seen', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('msg_receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('msg_sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
